name: Extractor Diario SEACE y Minería Real

on:
  schedule:
    - cron: '0 11 * * *' # 6:00 AM Hora Perú
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Copiar repositorio
      uses: actions/checkout@v2
      
    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Instalar librerías
      run: pip install requests
      
    - name: Ejecutar Ambos Extractores
      run: |
        python extractor.py
        python extractor_minero.py
      
    - name: Guardar cambios en GitHub
      run: |
        git config --global user.name 'Robot Extractor Grupo J3'
        git config --global user.email 'bot@grupoj3.com'
        git add oportunidades_sur.json oportunidades_mineras.json
        git commit -m "Actualización automática SEACE y Minería del Sur" || exit 0
        git push
